name: pull request
on:
  pull_request:
    branches:
      - master
      - main

jobs:
  shared-operator-workflow:
    name: shared-operator-workflow
    uses: redhat-cop/github-workflows-operators/.github/workflows/release-operator.yml@6005dbbf6e4349cd92304439eb34518080086f62 # v1.1.0
    with: 
      RUN_UNIT_TESTS: true
      RUN_INTEGRATION_TESTS: true
      RUN_HELMCHART_TEST: true
      GO_VERSION: ~1.21
      OPERATOR_SDK_VERSION: v1.25.3
