name: pull request
on:
  pull_request:
    branches:
      - master
      - main

jobs:
  shared-operator-workflow:
    name: shared-operator-workflow
    uses: raffaelespazzoli/github-workflows-operators/.github/workflows/pr-operator.yml@cosign
    with: 
      RUN_UNIT_TESTS: true
      RUN_INTEGRATION_TESTS: true
      RUN_HELMCHART_TEST: true
      GO_VERSION: ~1.19
      OPERATOR_SDK_VERSION: v1.25.3
